### PR TITLE
Added New Feature (Greet New Members)

### PR DESCRIPTION
**Pull request by namanmadan**
Greet New Group Members.
Self-Introduction When added to group.

### CODE REVIEW

**Review by realslimshanky — CHANGES_REQUESTED** [review]
I'm getting a warning while running the bot `UserWarning: Using a list of filters in MessageHandler is getting deprecated, please use bitwise operators (& and |) instead. More info: https://git.io/vPTbc.
  warnings.warn('Using a list of filters in MessageHandler is getting '`
Please resolve this by following the message.

**Comment by namanmadan** [comment]
Issue Resolved !!

**Comment by realslimshanky** [comment]
I'm getting following error while running the code
`2017-12-11 19:13:00,046 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/home/realslimshanky/.local/share/virtualenvs/PyData-Delhi-Bot-UrNKyq0Q/lib/python3.5/site-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "/home/realslimshanky/.local/share/virtualenvs/PyData-Delhi-Bot-UrNKyq0Q/lib/python3.5/site-packages/telegram/ext/messagehandler.py", line 123, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "pyddbot.py", line 222, in empty_message
    return welcome(bot, update)
  File "pyddbot.py", line 205, in welcome
    send_async(bot, chat_id=chat_id, text=text, parse_mode=ParseMode.HTML)
NameError: name 'send_async' is not defined
`
This might be because of the version of telegram-python-bot package. Please state which version are you using.

**Comment by namanmadan** [comment]
send_async was missing.

**Comment by namanmadan** [comment]
send_async was missing.

**Review by realslimshanky — CHANGES_REQUESTED** [review]
The new changes work perfectly.

**Review by realslimshanky — APPROVED** [review]
The new changes work perfectly.

**Comment by realslimshanky** [comment]
Thanks for your contribution @namanmadan

**Pull request merged**
